import marimo

__generated_with = "0.20.1"
app = marimo.App(width="full")


@app.cell
def _():
    import marimo as mo

    import matplotlib.pyplot as plt
    import numpy as np
    import seaborn as sns
    from sklearn.cluster import HDBSCAN
    from sklearn.datasets import make_blobs, make_circles
    from sklearn.metrics.pairwise import euclidean_distances

    sns.set_style("whitegrid")
    return HDBSCAN, euclidean_distances, make_blobs, make_circles, mo, np, plt, sns


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Clustering: Unsupervised Learning

    In supervised learning we have labeled data and train models to predict those labels.
    **Clustering** is an *unsupervised* technique: we have only feature data and want to
    discover natural groupings without any target variable.

    This notebook covers two clustering algorithms:

    1. **K-Means** — a centroid-based method that partitions data into $k$ spherical clusters
    2. **HDBSCAN** — a density-based method that finds clusters of arbitrary shape and identifies noise

    We will see where K-Means works well, where it breaks down, and how density-based
    methods address those limitations.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Synthetic Blob Data

    We start with a simple scenario: five well-separated, roughly spherical clusters
    generated by `make_blobs`. This is the kind of data K-Means was designed for.
    """)
    return


@app.cell
def _(make_blobs, plt, sns):
    blob_features, blob_labels = make_blobs(
        n_samples=1_000,
        centers=5,
        random_state=42,
    )

    _fig, _ax = plt.subplots(figsize=(8, 5))

    sns.scatterplot(
        x=blob_features[:, 0],
        y=blob_features[:, 1],
        hue=blob_labels,
        edgecolor="k",
        alpha=0.75,
        ax=_ax,
    )
    _ax.set_xlabel("Feature 1")
    _ax.set_ylabel("Feature 2")
    _ax.set_title("Blob Data — True Labels")
    _ax.legend(
        title="Cluster",
        bbox_to_anchor=(1.01, 1.01),
        loc="upper left",
    )

    plt.tight_layout()
    plt.show()
    return blob_features, blob_labels


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## K-Means Algorithm

    K-Means partitions $n$ observations into $k$ clusters by iteratively minimizing the
    **within-cluster sum of squares (WCSS)**:

    $$
    \text{WCSS} = \sum_{j=1}^{k} \sum_{\mathbf{x}_i \in C_j} \| \mathbf{x}_i - \boldsymbol{\mu}_j \|^2
    $$

    where $C_j$ is the set of points assigned to cluster $j$ and $\boldsymbol{\mu}_j$ is
    the centroid of that cluster.

    **Steps:**

    1. Randomly select $k$ data points as initial centroids.
    2. **Assign** each point to the nearest centroid.
    3. **Update** each centroid to be the mean of its assigned points.
    4. Repeat steps 2–3 until the change in WCSS falls below a threshold.
    """)
    return


@app.cell
def _(blob_features, euclidean_distances, np, plt, sns):
    N_CLUSTERS = 5
    CONVERGENCE_THRESHOLD = 1.0

    np.random.seed(42)

    _random_rows = np.random.choice(
        a=len(blob_features),
        size=N_CLUSTERS,
        replace=False,
    )
    _centers = blob_features[_random_rows].copy()

    _delta_wcss = np.inf
    _best_wcss = None

    while _delta_wcss > CONVERGENCE_THRESHOLD:
        _center_distances = euclidean_distances(
            blob_features,
            _centers,
        )
        blob_cluster_assignments = np.argmin(_center_distances, axis=1)

        _wcss = 0
        for _cluster_id in np.unique(blob_cluster_assignments):
            _mask = blob_cluster_assignments == _cluster_id
            _distances = euclidean_distances(
                blob_features[_mask],
                _centers[_cluster_id].reshape(1, -1),
            )
            _wcss += (_distances.flatten() ** 2).sum()

        for _cluster_id in np.unique(blob_cluster_assignments):
            _mask = blob_cluster_assignments == _cluster_id
            _centers[_cluster_id] = blob_features[_mask].mean(axis=0)

        if _best_wcss is None:
            _delta_wcss = _wcss
        else:
            _delta_wcss = _best_wcss - _wcss
        _best_wcss = _wcss

    _fig, _ax = plt.subplots(figsize=(8, 5))

    sns.scatterplot(
        x=blob_features[:, 0],
        y=blob_features[:, 1],
        hue=blob_cluster_assignments,
        edgecolor="k",
        alpha=0.75,
        ax=_ax,
    )
    _ax.set_xlabel("Feature 1")
    _ax.set_ylabel("Feature 2")
    _ax.set_title("K-Means on Blob Data (k=5)")
    _ax.legend(
        title="Cluster",
        bbox_to_anchor=(1.01, 1.01),
        loc="upper left",
    )

    plt.tight_layout()
    plt.show()
    return (blob_cluster_assignments,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## The Elbow Method

    K-Means requires us to choose $k$ in advance. The **elbow method** helps by plotting
    WCSS against $k$: as $k$ increases, WCSS always decreases, but the rate of decrease
    slows. The "elbow" — the point where adding another cluster yields diminishing returns —
    suggests a good choice for $k$.
    """)
    return


@app.cell
def _(blob_features, euclidean_distances, np, plt):
    K_RANGE = range(1, 11)
    ELBOW_CONVERGENCE_THRESHOLD = 1.0

    _wcss_values = []

    for _k in K_RANGE:
        np.random.seed(42)

        _random_rows = np.random.choice(
            a=len(blob_features),
            size=_k,
            replace=False,
        )
        _centers = blob_features[_random_rows].copy()

        _delta_wcss = np.inf
        _best_wcss = None

        while _delta_wcss > ELBOW_CONVERGENCE_THRESHOLD:
            _center_distances = euclidean_distances(
                blob_features,
                _centers,
            )
            _assignments = np.argmin(_center_distances, axis=1)

            _wcss = 0
            for _cluster_id in np.unique(_assignments):
                _mask = _assignments == _cluster_id
                _distances = euclidean_distances(
                    blob_features[_mask],
                    _centers[_cluster_id].reshape(1, -1),
                )
                _wcss += (_distances.flatten() ** 2).sum()

            for _cluster_id in np.unique(_assignments):
                _mask = _assignments == _cluster_id
                _centers[_cluster_id] = blob_features[_mask].mean(axis=0)

            if _best_wcss is None:
                _delta_wcss = _wcss
            else:
                _delta_wcss = _best_wcss - _wcss
            _best_wcss = _wcss

        _wcss_values.append(_best_wcss)

    _fig, _ax = plt.subplots(figsize=(8, 5))
    _ax.plot(
        list(K_RANGE),
        _wcss_values,
        marker="o",
        color="steelblue",
        linewidth=2,
    )
    _ax.set_xlabel("Number of Clusters (k)")
    _ax.set_ylabel("WCSS")
    _ax.set_title("Elbow Method — WCSS vs. k")
    _ax.set_xticks(list(K_RANGE))

    plt.tight_layout()
    plt.show()
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## When K-Means Fails: Concentric Circles

    K-Means assumes clusters are convex and roughly spherical. When the true structure is
    non-convex — such as concentric rings — K-Means cannot recover the correct groupings
    regardless of $k$.

    Below we generate two concentric circles and visualize the true labels.
    """)
    return


@app.cell
def _(make_circles, plt, sns):
    circle_features, circle_labels = make_circles(
        n_samples=1_000,
        noise=0.05,
        factor=0.5,
        random_state=42,
    )

    _fig, _ax = plt.subplots(figsize=(8, 5))

    sns.scatterplot(
        x=circle_features[:, 0],
        y=circle_features[:, 1],
        hue=circle_labels,
        edgecolor="k",
        alpha=0.75,
        ax=_ax,
    )
    _ax.set_xlabel("Feature 1")
    _ax.set_ylabel("Feature 2")
    _ax.set_title("Circle Data — True Labels")
    _ax.legend(
        title="Ring",
        bbox_to_anchor=(1.01, 1.01),
        loc="upper left",
    )

    plt.tight_layout()
    plt.show()
    return circle_features, circle_labels


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### K-Means on Circles

    With $k=2$, K-Means will split the data along a linear boundary rather than
    recognizing the ring structure. The algorithm minimizes WCSS, which favors
    compact, ball-shaped clusters — exactly the wrong inductive bias for this geometry.
    """)
    return


@app.cell
def _(circle_features, euclidean_distances, np, plt, sns):
    CIRCLE_K = 2
    CIRCLE_CONVERGENCE_THRESHOLD = 1.0

    np.random.seed(42)

    _random_rows = np.random.choice(
        a=len(circle_features),
        size=CIRCLE_K,
        replace=False,
    )
    _centers = circle_features[_random_rows].copy()

    _delta_wcss = np.inf
    _best_wcss = None

    while _delta_wcss > CIRCLE_CONVERGENCE_THRESHOLD:
        _center_distances = euclidean_distances(
            circle_features,
            _centers,
        )
        _circle_kmeans_assignments = np.argmin(_center_distances, axis=1)

        _wcss = 0
        for _cluster_id in np.unique(_circle_kmeans_assignments):
            _mask = _circle_kmeans_assignments == _cluster_id
            _distances = euclidean_distances(
                circle_features[_mask],
                _centers[_cluster_id].reshape(1, -1),
            )
            _wcss += (_distances.flatten() ** 2).sum()

        for _cluster_id in np.unique(_circle_kmeans_assignments):
            _mask = _circle_kmeans_assignments == _cluster_id
            _centers[_cluster_id] = circle_features[_mask].mean(axis=0)

        if _best_wcss is None:
            _delta_wcss = _wcss
        else:
            _delta_wcss = _best_wcss - _wcss
        _best_wcss = _wcss

    _fig, _ax = plt.subplots(figsize=(8, 5))

    sns.scatterplot(
        x=circle_features[:, 0],
        y=circle_features[:, 1],
        hue=_circle_kmeans_assignments,
        edgecolor="k",
        alpha=0.75,
        ax=_ax,
    )
    _ax.set_xlabel("Feature 1")
    _ax.set_ylabel("Feature 2")
    _ax.set_title("K-Means on Circle Data (k=2)")
    _ax.legend(
        title="Cluster",
        bbox_to_anchor=(1.01, 1.01),
        loc="upper left",
    )

    plt.tight_layout()
    plt.show()
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## HDBSCAN: Density-Based Clustering

    **HDBSCAN** (Hierarchical Density-Based Spatial Clustering of Applications with Noise)
    addresses K-Means' limitations:

    | | K-Means | HDBSCAN |
    |---|---------|---------|
    | **Number of clusters** | Must specify $k$ | Determined automatically |
    | **Cluster shape** | Spherical / convex | Arbitrary |
    | **Noise handling** | Every point assigned | Noise points labeled $-1$ |
    | **Core idea** | Minimize WCSS to centroids | Find dense regions separated by sparse areas |

    HDBSCAN works by estimating the density around each point and grouping together points
    that are in contiguous high-density regions. Points in low-density regions are classified
    as noise.
    """)
    return


@app.cell
def _(HDBSCAN, circle_features, plt, sns):
    _clusterer = HDBSCAN()
    _clusterer.fit(circle_features)

    _fig, _ax = plt.subplots(figsize=(8, 5))

    sns.scatterplot(
        x=circle_features[:, 0],
        y=circle_features[:, 1],
        hue=_clusterer.labels_,
        edgecolor="k",
        alpha=0.75,
        ax=_ax,
    )
    _ax.set_xlabel("Feature 1")
    _ax.set_ylabel("Feature 2")
    _ax.set_title("HDBSCAN on Circle Data")
    _ax.legend(
        title="Cluster",
        bbox_to_anchor=(1.01, 1.01),
        loc="upper left",
    )

    plt.tight_layout()
    plt.show()
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Summary

    | Aspect | K-Means | HDBSCAN |
    |--------|---------|---------|
    | **When to use** | Well-separated, spherical clusters | Arbitrary shapes, unknown $k$ |
    | **Key parameter** | $k$ (number of clusters) | `min_cluster_size` |
    | **Strengths** | Simple, fast, interpretable | No $k$ required, handles noise, flexible shapes |
    | **Weaknesses** | Assumes spherical clusters, sensitive to $k$ | Slower on large data, density assumptions |
    | **Diagnostic tool** | Elbow method (WCSS vs. $k$) | Cluster persistence plot |
    """)
    return


@app.cell
def _():
    return


if __name__ == "__main__":
    app.run()
